# Run before ESP-IDF reads the active configuration or initializes its target.
function(solar_os_regenerate_stale_sdkconfig)
    if(SDKCONFIG)
        get_filename_component(config "${SDKCONFIG}" ABSOLUTE)
    else()
        set(config "${CMAKE_SOURCE_DIR}/sdkconfig")
    endif()
    if(NOT EXISTS "${config}")
        return()
    endif()
    file(STRINGS "${config}" bluetooth_enabled REGEX "^CONFIG_BT_ENABLED=y$")
    file(STRINGS "${config}" nimble_enabled REGEX "^CONFIG_BT_NIMBLE_ENABLED=y$")
    if(bluetooth_enabled AND NOT nimble_enabled)
        get_filename_component(config_name "${config}" NAME)
        if(config_name MATCHES "^sdkconfig\\.defaults($|\\.)")
            message(FATAL_ERROR "SDKCONFIG must select a generated configuration, not defaults: ${config}")
        endif()
        message(NOTICE
            "SolarOS BLE requires NimBLE; removing stale ${config} and regenerating from SDK configuration defaults")
        file(REMOVE "${config}")
    endif()
endfunction()
